export type GrowthPage = { path: string; title: string; description: string; h1: string; audience: string; intro: string;
  sections: { title: string; paragraphs: string[]; items?: string[] }[]; faq: [string, string][]; related: [string, string][];
  reviewedOn?: string; sources?: [string, string][];
  comparison?: { caption: string; headers: string[]; rows: string[][] } };

export const buyerPages: GrowthPage[] = [
  {
    path: "/white-label-crypto-swap", title: "White Label Crypto Swap Software | Branded Deployment",
    description: "License a branded non-custodial swap experience with wallet connections, quote review, tracking and alerts. Explore a no-wallet demo and scope a paid pilot.",
    h1: "White label crypto swap software", audience: "For teams launching a branded swap experience",
    intro: "License existing non-custodial swap software, launch it under your brand and keep control of your deployment. For wallet teams, crypto products and agencies: a working customer journey, scoped integration, acceptance testing and handover.",
    sections: [
      { title: "More than a token selector", paragraphs: ["The visible swap form is only one part of delivery. A usable experience also has to handle wallet handoffs, account and network changes, expiring quotes, approvals, recipient checks and transaction progress. Reusing that workflow lets your team concentrate on the product around it.", "The current implementation includes browser and mobile wallet connections, searchable tokens, provider-normalized quote review, saved history, favorite pairs and alerts. Supported routes use approved providers; it is not a promise that every asset pair is available."] },
      { title: "What a branded deployment includes", paragraphs: ["A pilot starts with one customer brand and one isolated deployment. We agree a named network/provider scope, configure the existing product, run acceptance checks and hand over build and operating documentation. Branding is configuration, not an unlimited bespoke redesign."], items: ["Your brand and domain, with separately scoped integration", "Your infrastructure, database, secrets and approved provider accounts", "Wallet-to-review screens, delivery states and protected operations views", "Acceptance criteria, release checks and a defined handover"] },
      { title: "Not a complete white-label exchange", paragraphs: ["This is licensed software for a non-custodial swap experience. It does not include a centralized order book, customer custody, liquidity provision, fiat banking, market making or a regulatory license. Users retain their private keys and approve ordinary swaps in their own wallets.", "Your team remains the operator. Provider approvals, supported routes, infrastructure costs and applicable permissions must be checked before launch. Core software rights are non-exclusive; source access and redistribution rights belong in the written agreement."] },
      { title: "Evaluate before committing", paragraphs: ["Use the synthetic demo to inspect the quote and fee review, wallet-request guidance, transaction states and Market Radar demonstration without connecting a wallet. Radar illustrates observed liquidity structure; commercial live exchange data is not included without suitable data rights.", "Then send your product website, intended users and required networks. We will check what already fits, identify integration work and define a paid pilot. No quantified time saving or launch date is assumed before that review."] }
    ],
    faq: [["Do I receive an exclusive product?", "No. The proposed model is a non-exclusive license to the reusable core plus scoped setup. Ownership, source access, allowed modifications and deployment rights must be agreed in writing."], ["Do you supply liquidity or provider approval?", "No. Routing uses supported third-party providers. The operator supplies approved accounts and accepts their terms. Buying software does not guarantee access to a route."], ["Can I try it without funds?", "Yes. The public demo uses sample data and sends no transactions, orders or wallet requests."]],
    related: [["/for-web3-agencies", "Deliver a client deployment"], ["/crypto-swap-integration", "Inspect integration boundaries"], ["/guides/build-vs-license-crypto-swaps", "Compare licensed software, provider widgets and a custom build"]]
  },
  {
    path: "/crypto-swap-integration", title: "Crypto Swap Integration for Existing Web3 Products",
    description: "Add a non-custodial swap workflow to an existing product. Review wallet, quote, backend and provider boundaries before scoping a branded integration.",
    h1: "Crypto swap integration", audience: "For product engineers and technical decision makers",
    intro: "Add an existing non-custodial swap workflow to your product: wallet connection, quote review, transaction tracking and operational evidence. License a branded deployment and scope the integration around your users and architecture.",
    sections: [
      { title: "An API response is not a complete user journey", paragraphs: ["A provider can return a route and transaction data. Your product still has to explain approvals, show what the user will receive, handle quote expiry and rejected wallet requests, and distinguish submission from completion. Those are the parts you can evaluate in our working demo.", "Swap Assistant uses a Next.js/React frontend for the user workflow and server-side quote handling, with a Spring Boot/PostgreSQL backend for authenticated history, preferences, alerts and operations. Provider credentials remain server-side. Integration starts by mapping these boundaries to your existing product."] },
      { title: "Define the interface with your team", paragraphs: ["We first review how users enter the swap flow, which wallet model you use, the networks and assets that matter, and where the result belongs in your product. A linked branded deployment may be enough; deeper embedding or native mobile work needs a separate scope."], items: ["Entry point, branding and return navigation", "Wallet and recipient compatibility on desktop and mobile", "Quote expiry, slippage, approvals and minimum-received review", "History, notifications, infrastructure ownership and acceptance tests"] },
      { title: "Same-chain and cross-chain are different integrations", paragraphs: ["Supported same-chain routes use configured providers such as 0x. Supported cross-chain routes use LI.FI and require additional recipient, network and delivery-state checks. Source-chain confirmation is not proof that destination funds have arrived.", "Availability depends on current provider support, account permissions, amount, assets and route conditions. We agree testable route examples rather than promise all tokens on all chains. A failed quote must remain a clear failure, not a route invented by the interface."] },
      { title: "Review security as a boundary, not a badge", paragraphs: ["The existing code includes validation, origin controls, rate limits, protected administration, automated tests and release checks. Fee reporting separates expected amounts from independently evidenced settlement. These controls are inspectable; they are not a claim of independent certification or zero risk.", "Users sign ordinary swaps in their wallets. Supported limit orders are a separate, explicitly signed protocol flow. Market Radar does not execute trades. Your own security and legal review, provider onboarding and real acceptance tests remain part of deployment readiness."] }
    ],
    faq: [["Can we install a Swap Assistant SDK?", "There is no generally available public SDK offer. We license the existing application and scope integration with your product. Native or headless interfaces must be evaluated, not assumed."], ["Can you reuse our existing wallet?", "Possibly. We review the wallet connector, signing methods, networks and mobile return flow during scoping. A compatible brand does not by itself prove compatible signing behavior."], ["Will integration avoid every provider dependency?", "No. Quote routing and execution still depend on external providers and blockchain networks. Your deployment needs appropriate accounts, limits and operating arrangements."]],
    related: [["/guides/non-custodial-swap-architecture", "Architecture and trust boundaries"], ["/for-wallets", "Wallet-specific evaluation"], ["/white-label-crypto-swap", "Branded deployment scope"]]
  },
  {
    path: "/for-wallets", title: "Crypto Swap Software for Wallet Products",
    description: "Evaluate a reusable swap experience for your wallet product: account changes, quote review, recipient checks and transaction states, without connecting a wallet to the demo.",
    h1: "Swap software for wallet products", audience: "For wallet teams with an existing product",
    intro: "Add an understandable swap journey without treating a provider quote as the finished feature. Start by comparing your wallet requirements with the existing review, recipient and delivery flows.",
    sections: [
      { title: "Protect the journey you already own", paragraphs: ["Your users know your wallet. A swap integration should respect their selected account, explain why a network change is needed and show what they are about to approve. A disconnected wallet or a rejected request should leave a clear next step.", "Swap Assistant already includes wallet selection, mobile handoff guidance, token/network-aware inputs, recipient handling and quote review. These are reusable application flows, not a replacement for your wallet key-management system."] },
      { title: "Review the difficult states first", paragraphs: ["Before agreeing a pilot, walk through the edge cases with your engineering team. The safe demo shows the review experience; an agreed technical test plan checks real connector compatibility separately."], items: ["User changes account or network after requesting a quote", "Quote expires while the wallet app is open", "Token approval is needed before swap approval", "Destination wallet differs from the source wallet", "Source transaction succeeds but cross-chain delivery is still pending"] },
      { title: "What remains in your control", paragraphs: ["Users keep their keys and approve ordinary swaps inside their wallet. Your team controls the customer deployment and provider accounts. Wallet sign-in protects saved history and preferences; it is not authorization to move funds.", "The application can expose configured platform fees transparently, with independent fee evidence in protected operations reporting. This is not a guarantee of income or settlement. Provider terms and actual route support determine what is possible."] },
      { title: "Start with a specific wallet use case", paragraphs: ["Tell us whether your product is web, extension or mobile, which signing interface it exposes, and a small set of required routes. Existing web behavior can be demonstrated immediately. Native embedding, new connectors and unsupported protocols are not silently included.", "A pilot should end with a documented acceptance result for your supported flow, not just a branded screenshot. Scope includes deployment and handover; ongoing maintenance and custom work are agreed separately."] }
    ],
    faq: [["Is this a wallet creation or custody service?", "No. It is a swap experience intended to work with compatible wallets. We do not generate or hold your users' private keys."], ["Can we evaluate without connecting our wallet?", "Yes. The synthetic demo needs no account or wallet and does not send transactions. Connector testing is a separate agreed step."], ["Does the product support every token?", "No universal coverage is promised. Tokens, networks, amounts, provider policy and available liquidity determine eligible routes."]],
    related: [["/guides/add-swaps-to-a-wallet", "Wallet integration checklist"], ["/crypto-swap-integration", "Technical integration scope"], ["/business", "The offer for teams"]]
  },
  {
    path: "/for-web3-agencies", title: "Branded Crypto Swap Software for Web3 Agencies",
    description: "Reuse a tested swap workflow for a client project. Agree one licensed branded deployment, provider scope, acceptance tests and handover instead of rebuilding every flow.",
    h1: "Crypto swap software for Web3 agencies", audience: "For agencies delivering wallet and DeFi products",
    intro: "Deliver a branded swap experience for a client without rebuilding the wallet-to-review workflow. License the existing application for a defined client deployment, then focus your team on the surrounding product and integration.",
    sections: [
      { title: "A reusable starting point for a real brief", paragraphs: ["Agency projects often share the same difficult plumbing: wallet handoffs, quote normalization, approval messages, transaction states and operational visibility. Swap Assistant brings those flows together so your team can inspect them before choosing whether to reuse them.", "This is most relevant when a client already has an audience, a product brief and an identified operator. It is less useful when the brief requires a new exchange matching engine, custody platform, bespoke protocol or an untested network."] },
      { title: "Separate your work from the reusable core", paragraphs: ["We agree what comes from the existing software and what your agency or a separate scope will implement. That division makes estimation and acceptance more concrete without inventing a calendar saving."], items: ["Existing core: wallet connection, quote and fee review, activity and alerts", "Configuration: brand, supported providers and named networks", "Client responsibilities: accounts, legal permissions and infrastructure", "Agency scope: surrounding product, bespoke UX and any additional integrations"] },
      { title: "A clear client handover", paragraphs: ["The starting offer covers one brand and one isolated customer-owned deployment. Agree the allowed modifications, source access, acceptance cases and support window alongside your client brief. Additional client deployments, sublicensing and source redistribution require explicit written rights; they are not included automatically.", "The client remains the operator and supplies approved provider accounts and secrets. We do not provide liquidity, legal clearance or managed custody. Infrastructure and provider costs are not bundled into a promise of permanently free operation."] },
      { title: "Make the pilot easy to evaluate", paragraphs: ["Send a short, non-confidential brief with the client category, required routes and intended handover. We can begin by email and use the synthetic demo to establish fit; a call is optional.", "A useful pilot has named acceptance cases, a deployment boundary and a written defect-correction window. Commercial live Radar feeds remain outside the offer unless data rights are approved; its synthetic demo can be discussed as a capability demonstration."] }
    ],
    faq: [["Can we present it under a client's brand?", "Yes, subject to an agreed license and scope for that deployment. The reusable core remains non-exclusive."], ["Are you replacing our development team?", "No. The offer is reusable application software and scoped integration/setup. Your team can own the surrounding product and client relationship under the agreed terms."], ["Can we resell it to multiple clients?", "Not under the default single-deployment scope. Sublicensing, redistribution and additional deployments need explicit written rights."]],
    related: [["/white-label-crypto-swap", "What the branded deployment includes"], ["/guides/build-vs-license-crypto-swaps", "Scope the work avoided and retained"], ["/crypto-swap-integration", "Review the implementation boundaries"]]
  }
];

export const guidePages: GrowthPage[] = [
  {
    path: "/guides/build-vs-license-crypto-swaps", title: "Crypto Swap Software vs Widgets vs Custom Build",
    description: "A practical checklist for choosing a provider widget, a custom swap implementation or licensed application software. Compare engineering scope, ownership and ongoing dependencies.",
    h1: "Build vs license a crypto swap experience", audience: "Software, provider widgets and API integration compared",
    intro: "Start with the workflow you need to own. A widget, a routing API and a licensed application solve different parts of the problem. None removes your responsibility for the product you operate.",
    reviewedOn: "2026-09-25",
    comparison: { caption: "What each approach actually delivers", headers: ["Decision", "Provider widget", "Custom API integration", "Licensed application"], rows: [
      ["Starting point", "Provider-maintained swap surface", "Routes and transaction-building interfaces", "Existing screens, backend and operating workflow"],
      ["Interface control", "Within the widget's supported options", "Your team builds and maintains it", "Brand the existing flow; scope deeper changes"],
      ["Wallet and failure states", "Check the widget's actual connector behavior", "Implement account changes, rejection, expiry and recovery", "Reuse demonstrated states; verify your wallet compatibility"],
      ["History and operations", "Check included services and data access", "Build persistence, notifications and evidence", "Existing modules, configured for the agreed deployment"],
      ["Ongoing work", "Vendor updates plus integration testing", "Your code, dependencies and provider changes", "Release ownership and maintenance agreed in writing"],
      ["Best fit to evaluate", "A limited embed with acceptable vendor UX", "A distinctive workflow with a funded engineering team", "A product or agency reusing an established workflow"]
    ] },
    sources: [["https://0x.org/products/swap", "0x Swap API: routing integration and developer examples"],
      ["https://developers.uniswap.org/docs/trading/swapping-api/start-building/integration-guide", "Uniswap integration guide: wallet, API-key, approval and transaction responsibilities"]],
    sections: [
      { title: "Compare deliverables, not feature counts", paragraphs: ["A widget can suit a team that needs a prebuilt surface and accepts the provider's UX and constraints. A routing API gives engineers more control but leaves the wallet, review, transaction states and support workflow to implement. A licensed application can provide those surrounding flows while introducing its own integration and maintenance obligations.", "Ask for a demonstration of the actual approval and failure paths. Two offers that both say 'cross-chain swaps' may differ substantially in recipient validation, pending-delivery handling and the evidence used to report completion."] },
      { title: "Write down the work that stays with your team", paragraphs: ["For each option, record who owns the interface, wallet integration, provider credentials, deployment, monitoring, incident response and upgrades. Do not count an included API as an included operated product.", "In a Swap Assistant branded deployment, the reusable application includes quote review, saved activity, alerts and release controls. The customer supplies approved provider accounts and infrastructure. Bespoke connectors, new protocols, operating permission and ongoing service levels are not assumed."] },
      { title: "Use a fit matrix before an estimate", paragraphs: ["Choose a small set of routes and wallet/device combinations representative of your users. For each one, classify the behavior as demonstrated, configurable, custom work or unsupported. Price the remaining work only after that distinction is visible."], items: ["Wallet connection, account switch, rejection and return-to-app behavior", "Allowance and swap approval boundaries", "Fee, network cost and minimum-received presentation", "Quote expiry and unavailable route handling", "Destination delivery and support investigation", "Deployment ownership, backup restore and release rollback"] },
      { title: "Compare a real brief, not a headline price", paragraphs: ["Consider an illustrative wallet team that needs a web swap journey for two named networks, one existing wallet connector, saved activity and Telegram alerts. A widget might cover quote and execution screens but still require separate activity and notification integration. A custom build gives control over all of it, with corresponding testing and maintenance work. Licensed software is useful only if its demonstrated behavior fits those requirements.", "Ask each supplier to classify every requirement as included, configuration, custom work or unavailable. Add infrastructure, provider fees or subscriptions, support, upgrades and acceptance testing to the comparison. Do not treat a lower initial license price as a lower total cost, or assume a supplier's public price covers your brief."] },
      { title: "Check rights and operating costs separately", paragraphs: ["A license should state deployment count, source access, allowed modifications, redistribution rights and the support window. Dependency and provider terms are separate from the application license. A fee configuration does not prove a provider account is approved or a payout has settled.", "Hosting, RPC, providers, notifications and market-data licensing can introduce ongoing costs even when the software uses free tiers initially. Ask for the current dependency map and limits, not a claim that operation will always be free."] },
      { title: "Make a paid pilot test a decision", paragraphs: ["A useful pilot ends with agreed acceptance evidence and a handover, not just a new logo. Set a bounded route scope, define pass/fail cases and identify the operator. If the requirements do not fit the existing implementation, custom development or a provider widget may be the better choice.", "There is no evidence-backed universal number of weeks saved. The honest saving is the implementation work your team can verify it does not need to repeat. Use the synthetic demo as the starting point, then request a scoped fit review."] }
    ], faq: [["Is licensing always cheaper?", "No. Custom requirements, operating obligations and license terms can change the comparison. Build a fit matrix and estimate the remaining work before deciding."], ["What should we request first?", "A working demo, explicit exclusions, architecture boundaries and acceptance criteria for your actual routes and wallets."]],
    related: [["/white-label-crypto-swap", "Inspect the licensed deployment offer"], ["/for-web3-agencies", "Scope an agency client project"], ["/guides/add-swaps-to-a-wallet", "Use the wallet acceptance checklist"], ["/business", "Evaluate the working software and paid-pilot offer"]]
  },
  {
    path: "/guides/add-swaps-to-a-wallet", title: "How to Add Crypto Swaps to an Existing Wallet",
    description: "Plan wallet-based swap integration from account selection through quote review, approvals and destination delivery. Includes a concrete acceptance-test example.",
    h1: "How to add crypto swaps to an existing wallet", audience: "A practical integration guide",
    intro: "The core question is not just which endpoint returns a quote. It is how the wallet user understands and authorizes each step, and how your product recovers when a step fails.",
    reviewedOn: "2026-09-25",
    sources: [["https://developers.uniswap.org/docs/trading/swapping-api/start-building/integration-guide", "Uniswap's official integration and transaction troubleshooting guide"]],
    sections: [
      { title: "1. Define the wallet and network contract", paragraphs: ["Identify the account selected by the user, supported signing methods and the current network. Review what happens when that account changes during a quote or approval. A token symbol is not enough to identify an asset: use its network and contract identifier, or the network's native-asset convention.", "For a cross-chain destination, the source wallet may not provide a suitable receiving address. Recipient collection and validation are a separate part of the workflow. Do not silently substitute an address on a different network."] },
      { title: "2. Request a route and normalize the review", paragraphs: ["Convert the entered amount using the asset's decimals. Treat the provider response as data that still needs validation. Present the asset, amount, destination, fee denomination, gas estimate, slippage bound and quote expiry together before asking for a signature.", "Expected output and minimum received serve different purposes. Network gas is also not necessarily paid in the same token as a platform fee. A meaningful review preserves these distinctions rather than collapsing everything into a misleading single number."] },
      { title: "3. Separate connection, sign-in and spending approval", paragraphs: ["Connecting exposes public wallet/account information. A sign-in message proves control for saved history or preferences. Neither should be described as approval to spend. A token allowance and the swap transaction are separate wallet actions when the selected route requires them.", "The existing Swap Assistant workflow keeps provider credentials server-side and asks the user's wallet to sign ordinary swaps. Exact provider-verifiable limit orders are a separate flow; do not mix their advance authorization into an ordinary login explanation."] },
      { title: "4. Design the non-happy paths", paragraphs: ["For a source amount of 100 USDC and a synthetic quote of 0.04 ETH, the interface can demonstrate amount, fee and minimum-received review without moving funds. In a real integration, the returned amounts come from a fresh route, not from that illustration.", "Your tests should deliberately reject a wallet prompt, expire the quote, switch account, use an incompatible recipient and simulate an unavailable provider. Each should leave the user with an accurate state and a bounded retry, not a success banner."], items: ["A rejected signature must not become a submitted transaction", "A refreshed route must be reviewed before approval", "Source confirmation must not imply cross-chain destination completion", "Repeated save requests must not double-count fee revenue"] },
      { title: "An acceptance checklist your product team can run", paragraphs: ["Record the selected wallet, network, token identifiers and software revision for each test. Use fixtures or a safe agreed test environment first; never put private keys, seed phrases or full signing payloads into a shared bug report."], items: [
        "Account switch: request a quote with account A, then switch to B. The old quote must not authorize a transaction for the wrong owner; request and review a fresh quote.",
        "User rejection: reject the allowance or swap request. Show a cancelled request, preserve editable inputs and do not record a transaction hash that was never broadcast.",
        "Expired quote: delay approval beyond its deadline. Do not retry obsolete calldata automatically; fetch a new quote and ask for review again.",
        "Allowance completed, swap rejected: report those as separate actions. Do not imply cancelling the swap revoked a previously granted allowance.",
        "Cross-chain delay: simulate a confirmed source transaction and pending destination delivery. Keep delivery pending; a source receipt alone is not completion.",
        "Duplicate notification: replay the same chain and transaction hash. Retain a single transaction identity, while allowing distinct genuine transactions to reconcile independently.",
        "Provider failure: simulate rate limiting or no route. Bound retries, retain clear unavailable states and never synthesize an executable route from a display price."
      ] },
      { title: "5. Agree ownership after launch", paragraphs: ["Decide who monitors provider outages, tests dependency updates, maintains wallet connectors and investigates delivery issues. Provider documentation describes its interface; your acceptance tests describe the behavior users actually depend on.", "A branded deployment can reuse the existing application workflow. Native embedding and a particular wallet's signing interface still need explicit scoping. Use the no-wallet demo to review the customer journey before a technical compatibility test."] }
    ], faq: [["Can we skip the backend?", "Some provider widgets can run with little application backend work. Saved user preferences, private credentials, alert delivery and durable operational evidence introduce server-side responsibilities. Choose based on the intended product."], ["Is connecting a wallet enough to authorize a swap?", "No. Ordinary swaps require the relevant wallet approval. A connection or login message must not be represented as spending permission."]],
    related: [["/for-wallets", "Evaluate Swap Assistant for a wallet"], ["/guides/non-custodial-swap-architecture", "Inspect tracking and fee-evidence architecture"], ["/crypto-swap-integration", "Scope the integration and acceptance plan"]]
  },
  {
    path: "/guides/non-custodial-swap-architecture", title: "Architecture of a Non-Custodial Swap Integration",
    description: "Trace wallet, frontend, provider and backend responsibilities in Swap Assistant. Understand cross-chain delivery, fee evidence, alerts and data-rights boundaries.",
    h1: "Architecture of a non-custodial swap integration", audience: "A concrete application example",
    intro: "Non-custodial describes a key-control boundary, not the absence of backend services. The following describes Swap Assistant's current application design, not a universal blueprint or independent security certification.",
    sections: [
      { title: "The user-authorized execution path", paragraphs: ["The browser collects the selected assets, networks, amount and recipient. Next.js server-side quote handling communicates with approved routing providers and normalizes the result. The review surface shows what the user is being asked to authorize. The connected wallet signs ordinary swap transactions; the application backend does not hold the user's private key."], items: ["User inputs -> quote validation -> approved provider route", "Normalized quote -> fee and minimum-received review -> wallet approval", "Submitted transaction -> chain/provider observations -> delivery status"] },
      { title: "The application-data boundary", paragraphs: ["Spring Boot and PostgreSQL store wallet-authenticated history, favorites and notification preferences. A wallet sign-in proves account control for these saved features. Admin operations use separate protection. Quoting and public product evaluation must not expose private user records.", "Email, Telegram and push use configured delivery services. These channels notify users; a price alert is not authorization to move funds. Duplicate handling, cooldowns and outbox delivery belong in this application layer rather than in the browser's success message."] },
      { title: "What changes for cross-chain delivery", paragraphs: ["A same-chain transaction receipt can establish a particular on-chain result. A cross-chain route needs source and destination progress tracked separately. Destination address compatibility, bridge/provider state and a possible refund are part of the delivery model.", "The current approved provider scope includes 0x and LI.FI routes where configured and supported. That is not a guarantee of all network combinations. A quote can become unavailable because of provider policy, liquidity, amount, account limits or network conditions."] },
      { title: "Revenue evidence is not browser telemetry", paragraphs: ["The implementation binds server-originated quote evidence to authenticated history and submitted transactions. Expected, not verified, accrued, received and failed are separate states. Independent reconciliation must support a verified fee result; a browser-reported confirmation alone cannot promote revenue.", "A cached quote may be reused by separate transactions. Each transaction needs its own identity and evidence. Conversely, receiving the same transaction twice must not create two fee records. This distinction is useful when evaluating any swap application's accounting claims."] },
      { title: "Keep market intelligence isolated", paragraphs: ["Market Radar has a separate collector boundary so exchange-feed failures do not need to interrupt authentication, contact enquiries or swap history. Its public demo is synthetic. Private Binance research access is not a commercial data license, and commercial live redistribution remains gated.", "Visible liquidity can move or disappear. Structural scores describe observed evidence, not a probability of profit or a guaranteed reversal. There is no automatic transition from Radar signal to trade execution."] },
      { title: "Review before deployment", paragraphs: ["The application has tests, validation, rate limits, protected administration and controlled release checks. A customer deployment still needs its own threat review, operator permissions, approved accounts, secret configuration, backup checks and acceptance evidence. Non-custody does not remove software, protocol or legal risk.", "Start with the isolated demo and an integration fit review. Agree the exact routes, interfaces, responsibilities and exclusions before selecting a pilot scope."] }
    ], faq: [["Does a server mean the application is custodial?", "Not by itself. The important distinction is who controls keys and spending authorization. Servers can store preferences, request quotes and reconcile evidence without signing ordinary swaps for users."], ["Is this an independently audited architecture?", "No independent audit or certification is claimed. Automated tests and internal review are evidence of engineering work, not a guarantee against vulnerabilities."]],
    related: [["/crypto-swap-integration", "Discuss a scoped integration"], ["/guides/build-vs-license-crypto-swaps", "Compare delivery approaches"], ["/market-radar", "Explore the synthetic Radar capability"]]
  }
];
